### ISSUE TITLE
Only support tuples and not single inputs/outputs

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/AbstractDifferentiation.jl#103]
The ambiguity between tuples and single inputs/outputs in pushforwards and pullbacks is causing several bugs (#99) and making the code more complicated.

I propose to make a breaking change that supports only tuples

cc @devmotion

**Comment by devmotion** [comment]
An alternative would be https://github.com/JuliaDiff/AbstractDifferentiation.jl/issues/53

**Comment by gdalle** [comment]
On second thought they're actually the same, replacing `args...` with `args` everywhere does the translation

**Comment by mohamed82008** [comment]
I think it should be fine to only support tuples. I don't recall why we support both but we can just support one.

**Comment by gdalle** [comment]
Only supporting plain inputs / outputs sounds slightly more natural though, doesn't it?

**Comment by mohamed82008** [comment]
that's also fine by me

**Comment by gdalle** [comment]
Closing this in favor of #53 then
