### ISSUE TITLE
Easy path to using anything with a ChainRulesCore.RuleConfig

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/AbstractDifferentiation.jl#11]
We have talked about this before, just writing it down so it doesn't get lost.
The [`ChainRulesCore.RuleConfig`](https://juliadiff.org/ChainRulesCore.jl/dev/config.html#Declaring-support-for-calling-back-into-ADs) with the right traits, provides all the parts needed for either getting the pushforward ([`frule_via_ad`](https://juliadiff.org/ChainRulesCore.jl/dev/api.html#ChainRulesCore.frule_via_ad)) or pullback ([`rrule_via_ad`](https://juliadiff.org/ChainRulesCore.jl/dev/api.html#ChainRulesCore.rrule_via_ad)); or both.
This primitives are enough to let AbstractDifferentiation.jl  define everything else.

Any ChainRules supporting AD that supports rules that require calling back into AD must define one of these.
[`Zygote.ZygoteRuleConfig`](https://github.com/FluxML/Zygote.jl/blob/355296e84f8b21c0f22204b0804af51653016137/src/compiler/chainrules.jl#L1) and [`Diffractor.DiffractorRuleConfig`](https://github.com/JuliaDiff/Diffractor.jl/blob/e2cfd85b88f02fce645ca1d9a51b16e9663c8aac/src/runtime.jl#L2)  for example.

Given such a `RuleConfig` type, it should be a one-liner to get the whole AbstractDifferentiation API.
We should provide a macro to make that so.

**Comment by gdalle** [comment]
I think this is now ReverseRuleBackend?

**Comment by schlichtanders** [comment]
Is there some progress here?

**Comment by gdalle** [comment]
I think it should be `ReverseRuleConfigBackend`? Can you post a MWE if what you're trying does not work?

**Comment by oxinabox** [comment]
Yeah this is basically done.
