### ISSUE TITLE
Inconsistency in value_and_pushforward_function vs value_and_pullback_function outputs

### ISSUE THREAD

**Issue by prbzrg** [JuliaDiff/AbstractDifferentiation.jl#119]
`value_and_pushforward_function` returns a function that returns `(value, pf)` 
https://github.com/JuliaDiff/AbstractDifferentiation.jl/blob/211b67528c5ed91971bb524c57adb63837163367/src/AbstractDifferentiation.jl#L259
but `value_and_pullback_function` returns `(value, pullback_function)`
https://github.com/JuliaDiff/AbstractDifferentiation.jl/blob/211b67528c5ed91971bb524c57adb63837163367/src/AbstractDifferentiation.jl#L319

**Comment by devmotion** [comment]
I'm not sure there's anything to be fixed here. In forward mode usually you get both the primal and the dual together vs in reverse mode you get the value and the pullback function (see, e.g., ForwardDiff or ChainRulesCore.frule vs Zygote or ChainRulesCore.rrule).

**Comment by prbzrg** [comment]
IMO, having a backend-agnostic interface means we shouldn't rely on backend APIs or mirror them. Moreover, every other value_and_AD APIs in `AbstractDifferentiation.jl` return value and AD.

**Comment by prbzrg** [comment]
And why do we return the same value every time?

**Comment by devmotion** [comment]
IMO the names are possibly confusing but not wrong per se - `value_and_X_function` can be read both as `(value_and_X)_function` and `value_and_(X_function)`. For forward mode we use the former interpretation and for reverse mode the latter.

AFAICT this difference between forward and reverse mode is not based on a specific package but a conceptual difference: In forward mode, you can (and usually do) compute both the primal value and the partial derivatives in a single forward path whereas in reverse mode you compute the primal value in the forward path, construct the pullback functions as you go, and then compute the derivatives in the backward path.

**Comment by prbzrg** [comment]
Thanks for your response.

**Comment by gdalle** [comment]
The docstring is misleading then, see #124 

That might be my fault
