### ISSUE TITLE
`value_and_pullback_function` doesn't do what its docstring says

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/AbstractDifferentiation.jl#124]
It returns `val, (tangents -> pullbacks)` instead of `tangents -> (val, pullbacks)`

For comparison, the forward equivalent does `tangents -> (val, pushforwards)` which is what it promises

**Comment by ToucheSir** [comment]
I recall this came up before, and the idea was that this returns a tuple of "value" and "pullback function" rather than a "value and pullback"-returning function. Certainly the former seems to make more sense when we're talking about split reverse mode AD?

**Comment by gdalle** [comment]
Regardless of what the best interpretation would be (I personally find this ambiguity horrifying), I think it would be good to fix the docstring first instead of changing the behavior. If you wanna review the associated PR #125 I can merge it afterwards :)

**Comment by ToucheSir** [comment]
You'll find no complaints from me there, not sure why it wasn't called e.g. `value_and_pullback` in the first place!
