### ISSUE TITLE
rename lazyderivative and friends to lazy_derivative

### ISSUE THREAD

**Issue by mohamed82008** [JuliaDiff/AbstractDifferentiation.jl#7]
Following @odow's comment in https://github.com/JuliaDiff/AbstractDifferentiation.jl/pull/5#discussion_r698075655, I think it's best to rename `lazyderivative` and friends to `lazy_derivative` and the likes to match the naming convention in the rest of the package.

**Comment by odow** [comment]
Others would be 
https://github.com/JuliaDiff/AbstractDifferentiation.jl/blob/4aca7387bf1c4d98bf4ba345f127fc88fbf79929/src/AbstractDifferentiation.jl#L17
https://github.com/JuliaDiff/AbstractDifferentiation.jl/blob/4aca7387bf1c4d98bf4ba345f127fc88fbf79929/src/AbstractDifferentiation.jl#L27
https://github.com/JuliaDiff/AbstractDifferentiation.jl/blob/4aca7387bf1c4d98bf4ba345f127fc88fbf79929/src/AbstractDifferentiation.jl#L32
https://github.com/JuliaDiff/AbstractDifferentiation.jl/blob/4aca7387bf1c4d98bf4ba345f127fc88fbf79929/src/AbstractDifferentiation.jl#L471
https://github.com/JuliaDiff/AbstractDifferentiation.jl/blob/4aca7387bf1c4d98bf4ba345f127fc88fbf79929/src/AbstractDifferentiation.jl#L474
https://github.com/JuliaDiff/AbstractDifferentiation.jl/blob/4aca7387bf1c4d98bf4ba345f127fc88fbf79929/src/AbstractDifferentiation.jl#L477

I also don't know what these one-letter structs are
https://github.com/JuliaDiff/AbstractDifferentiation.jl/blob/4aca7387bf1c4d98bf4ba345f127fc88fbf79929/src/AbstractDifferentiation.jl#L481
https://github.com/JuliaDiff/AbstractDifferentiation.jl/blob/4aca7387bf1c4d98bf4ba345f127fc88fbf79929/src/AbstractDifferentiation.jl#L495

**Comment by gdalle** [comment]
This is solved by #9
