### ISSUE TITLE
API Docs for end-users

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/AbstractDifferentiation.jl#92]
We don't seem to have API docs?

**Comment by gdalle** [comment]
There's the README, but do you mean an actual documentation website à la Documenter.jl?

**Comment by oxinabox** [comment]
Yes
 
Right now nothing explains what eg `gradient` or `hessian` is. What it's return types are etc

**Comment by gdalle** [comment]
Related issues:

- #10 
- #31
- #91

**Comment by oxinabox** [comment]
those are related.
But in particular I want API docs for `gradient`, `hessian`, `jacobian` etc etc.

**Comment by gdalle** [comment]
This is solved in the dev docs
